name: _3_versions_map_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.1
  firebase_auth: ^4.9.1
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.0.0  # Added for image uploads
  cupertino_icons: ^1.0.8
  mapbox_gl: ^0.16.0
  geolocator: ^12.0.0
  js: ^0.6.4

dependency_overrides:
  firebase_auth_web: ^5.8.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/user_location_web.png

  